#!/bin/bash
#
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2010, 2011, 2012, 2013, 2014, 2016 Synacor, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software Foundation,
# version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
# ***** END LICENSE BLOCK *****
#


usage() {
  echo "Usage: $0"
  exit 1
}

if [ x`whoami` != xzimbra ]; then
  echo Error: must be run as zimbra user
  exit 1
fi

source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars

download_dir=${mailboxd_directory}/webapps/zimbra/downloads
index=${download_dir}/index.html

admin_dir=${mailboxd_directory}/webapps/zimbraAdmin/WEB-INF/classes/messages
zmsg=${admin_dir}/ZaMsg.properties


exit 0
